import { sb } from '/js/supabase.js';
import { $, $$, esc, fmtDate, fmtPrice, toast, friendlyError, setLoading } from '/js/utils.js';
import { table, modal, confirmBox } from './ui.js';
export async function render(el) {
  const { data, error } = await sb.from('coupons').select('*').order('created_at', { ascending: false }); if (error) throw error;
  el.innerHTML = `<h1>Promotions et codes promo</h1><div class="toolbar"><button class="btn primary" id="add">Créer un code</button></div>${table(['Code', 'Réduction', 'Minimum', 'Utilisations', 'Expire', 'Actif', 'Actions'], data.map((c) => `<tr><td><strong>${esc(c.code)}</strong></td><td>${c.type === 'percent' ? `${c.value} %` : fmtPrice(c.value)}</td><td>${fmtPrice(c.min_subtotal)}</td><td>${c.used_count}${c.max_uses ? ` / ${c.max_uses}` : ''}</td><td>${c.expires_at ? fmtDate(c.expires_at) : '—'}</td><td>${c.is_active ? 'Oui' : 'Non'}</td><td><button class="btn ghost sm" data-t="${c.id}">${c.is_active ? 'Désactiver' : 'Activer'}</button> <button class="btn danger sm" data-d="${c.id}">Supprimer</button></td></tr>`))}`;
  $('#add').onclick = () => {
    const m = modal(`<h2>Nouveau code promo</h2><form id="f"><div class="field"><label for="c">Code</label><input id="c" required maxlength="30" style="text-transform:uppercase"></div><div class="two"><div class="field"><label for="t">Type</label><select id="t"><option value="percent">Pourcentage</option><option value="fixed">Montant fixe (G)</option></select></div><div class="field"><label for="v">Valeur</label><input id="v" type="number" min="1" step="0.01" required></div></div><div class="two"><div class="field"><label for="mn">Montant minimum (G)</label><input id="mn" type="number" min="0" value="0"></div><div class="field"><label for="mx">Utilisations max (facultatif)</label><input id="mx" type="number" min="1"></div></div><div class="field"><label for="ex">Date d’expiration (facultatif)</label><input id="ex" type="date"></div><p class="err-msg" id="e" role="alert"></p><div class="row"><button class="btn primary" id="s">Créer</button><button type="button" class="btn ghost" id="x">Annuler</button></div></form>`);
    m.querySelector('#x').onclick = () => m.remove();
    m.querySelector('#f').onsubmit = async (ev) => { ev.preventDefault(); const q = (s) => m.querySelector(s); const v = +q('#v').value; if (!q('#c').value.trim() || !(v > 0) || (q('#t').value === 'percent' && v > 100)) { q('#e').textContent = 'Vérifiez le code et la valeur (100 % maximum).'; return; } setLoading(q('#s'), true);
      const { error } = await sb.from('coupons').insert({ code: q('#c').value.trim().toUpperCase(), type: q('#t').value, value: v, min_subtotal: +q('#mn').value || 0, max_uses: q('#mx').value ? +q('#mx').value : null, expires_at: q('#ex').value ? new Date(q('#ex').value + 'T23:59:59').toISOString() : null }); setLoading(q('#s'), false);
      if (error) { q('#e').textContent = friendlyError(error); return; } m.remove(); toast('Code créé.'); render(el); };
  };
  $$('[data-t]').forEach((b) => (b.onclick = async () => { const c = data.find((x) => x.id === b.dataset.t); await sb.from('coupons').update({ is_active: !c.is_active }).eq('id', c.id); render(el); }));
  $$('[data-d]').forEach((b) => (b.onclick = async () => { if (await confirmBox('Supprimer ce code promo ?')) { await sb.from('coupons').delete().eq('id', b.dataset.d); render(el); } }));
}
